---
clusterName: "development"
nodeGroup: "ingest"

# Elasticsearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.master=true
roles:
  master: "false"
  ingest: "true"
  data: "false"

replicas: 1

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml and log4j2.properties
esConfig: 
  elasticsearch.yml: |
      xpack.monitoring.collection.enabled: true
#  log4j2.properties: |
#    key = value

image: "elasticsearch"
imageTag: "7.8.0"
imagePullPolicy: "IfNotPresent"
