elasticsearchHosts: "http://elasticsearch-master:9200"

replicas: 1

image: "kibana"
imageTag: "7.8.0"
imagePullPolicy: "IfNotPresent"

ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: nginx
  hosts:
    - kibana.testdomain.com.br
  tls: []
